### ISSUE TITLE
Provide support for Jersey 3.x

### ISSUE THREAD

**Issue by hankipanky** [nhenneaux/jersey-http2-jetty-connector#37]
Would it be possible to lift this to support Jersey 3.x?

**Comment by nhenneaux** [comment]
Hi Henning
Jetty HTTP/2 client integration with Jersey using this plugin is quite limited since it cannot handle both HTTP/1 and HTTP/2 servers.
Would it possible you use [Java native HTTP client jersey connector]( https://github.com/nhenneaux/jersey-httpclient-connecto) instead of this connector? It supports HTTP/1 & HTTP/2 and it doesn't need additional dependency for the HTTP client.

**Comment by hankipanky** [comment]
Hi Nicolas, Thanks for the quick response. I was using that before and am experiencing problems with it. To understand more and to compare, I was trying to find another HTTP/2 implementation. I might contact you about the original problem then, if that's ok. Happy for this to be closed - thanks! 
Cheers, Henning

**Comment by nhenneaux** [comment]
Thanks let me know if you experiment problem on this connector or httpclient connector.
